### ISSUE TITLE
DataMsg inside of DataMsg - dynamic_cast problem

### ISSUE THREAD

**Issue by martinwag** [khuttun/PolyM#5]
Hi,

I'm having a problem with using DataMsg template nested inside another DataMsg, like this:  `DataMsg<DataMsg<int>>`

My use case is to extract the nested _DataMsg_ and pass it on to another class. As I do not know the actual data type of _DataMsg_ yet, I'm starting by casting to the base Msg type like this:
```
function(Msg &base) {
    dynamic_cast<DataMsg<Msg>&>(base)
}
```
However, this cast fails with a bad cast exception. Doing the same using a static cast seems to work as expected (payload OK, no segfault).

From a polymorphic view point I can't see anything wrong with my approach. As dynamic casting works for the non-nested type, it should work for the nested one too?

Any ideas?

Thanks!

I've attached a minimalistic test program that shows the problem. This uses the Msg and DataMsg type with everyting removed that is not essential. 
Build and run with 
`g++ test.cpp -o test.x && ./test.x`

[test.zip](https://github.com/khuttun/PolyM/files/2556648/test.zip)

**Comment by khuttun** [comment]
I don't think such a cast would work. Types `DataMsg<DataMsg<int>>` and `DataMsg<Msg>` are not related. If you have only few possible actual types maybe you can try `dynamic_cast`ing to all of them, and check which one succeeds? Another possibility could be to change your design and wrap the inner `DataMsg` as `Msg` pointer in some struct, and use the struct as the outer `DataMsg` template argument.

**Comment by martinwag** [comment]
Thanks.

I'm now using a Msg like this:

`using NestedMsg = DataMsg<std::unique_ptr<Msg>>;`

and a nested Msg type like this:

```
    class EventMsgRep {
      public:
        std::string response;
    };
    using eventMsgResp_t = DataMsg<EventMsgRep>;
```
This can be generated with make_unique and set as payload with move.
